language: cpp
sudo: required
os:
  - linux
  - windows
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x install.sh; fi
install:
  - ./install.sh
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config release
